import type {
  Wine,
  WineRegion,
  Tweet,
  TrendItem,
} from "@/types/wine";

export const mockWines: Wine[] = [
  {
    id: "1",
    name: "Château Margaux 2018",
    nameJa: "シャトー・マルゴー 2018",
    producer: "Château Margaux",
    region: "Margaux, Bordeaux",
    country: "France",
    countryCode: "FR",
    vintage: 2018,
    type: "red",
    grapeVarieties: ["カベルネ・ソーヴィニヨン", "メルロー", "プティ・ヴェルド"],
    imageUrl: "/images/placeholder-wine.svg",
    description:
      "ボルドー左岸の至宝。力強さとエレガンスを兼ね備えた、熟成ポテンシャルの高い一本。",
    ratings: {
      vivino: 4.6,
      vivinoCount: 2847,
      wineSearcher: 97,
      cellarTracker: 96,
    },
    prices: [
      {
        source: "rakuten",
        sourceName: "楽天市場",
        price: 89800,
        url: "#",
        lastUpdated: "2026-03-18",
        inStock: true,
      },
      {
        source: "amazon",
        sourceName: "Amazon.co.jp",
        price: 92500,
        url: "#",
        lastUpdated: "2026-03-18",
        inStock: true,
      },
      {
        source: "enoteca",
        sourceName: "エノテカ",
        price: 95000,
        url: "#",
        lastUpdated: "2026-03-17",
        inStock: false,
      },
    ],
    priceHistory: [
      { date: "2025-09", price: 82000, source: "rakuten" },
      { date: "2025-10", price: 84000, source: "rakuten" },
      { date: "2025-11", price: 85500, source: "rakuten" },
      { date: "2025-12", price: 88000, source: "rakuten" },
      { date: "2026-01", price: 87000, source: "rakuten" },
      { date: "2026-02", price: 89000, source: "rakuten" },
      { date: "2026-03", price: 89800, source: "rakuten" },
    ],
  },
  {
    id: "2",
    name: "Opus One 2019",
    nameJa: "オーパス・ワン 2019",
    producer: "Opus One Winery",
    region: "Napa Valley",
    country: "USA",
    countryCode: "US",
    vintage: 2019,
    type: "red",
    grapeVarieties: ["カベルネ・ソーヴィニヨン", "メルロー", "カベルネ・フラン"],
    imageUrl: "/images/placeholder-wine.svg",
    description:
      "ナパ・ヴァレーを代表するアイコンワイン。豊かな果実味と複雑なアロマが特徴。",
    ratings: {
      vivino: 4.5,
      vivinoCount: 12540,
      wineSearcher: 95,
      cellarTracker: 94,
    },
    prices: [
      {
        source: "rakuten",
        sourceName: "楽天市場",
        price: 52800,
        url: "#",
        lastUpdated: "2026-03-18",
        inStock: true,
      },
      {
        source: "amazon",
        sourceName: "Amazon.co.jp",
        price: 54000,
        url: "#",
        lastUpdated: "2026-03-18",
        inStock: true,
      },
    ],
    priceHistory: [
      { date: "2025-09", price: 48000, source: "rakuten" },
      { date: "2025-10", price: 49500, source: "rakuten" },
      { date: "2025-11", price: 50000, source: "rakuten" },
      { date: "2025-12", price: 51000, source: "rakuten" },
      { date: "2026-01", price: 52000, source: "rakuten" },
      { date: "2026-02", price: 52500, source: "rakuten" },
      { date: "2026-03", price: 52800, source: "rakuten" },
    ],
  },
  {
    id: "3",
    name: "Cloudy Bay Sauvignon Blanc 2023",
    nameJa: "クラウディー・ベイ ソーヴィニヨン・ブラン 2023",
    producer: "Cloudy Bay",
    region: "Marlborough",
    country: "New Zealand",
    countryCode: "NZ",
    vintage: 2023,
    type: "white",
    grapeVarieties: ["ソーヴィニヨン・ブラン"],
    imageUrl: "/images/placeholder-wine.svg",
    description:
      "ニュージーランドを代表する白ワイン。グレープフルーツやパッションフルーツの鮮やかなアロマ。",
    ratings: {
      vivino: 4.0,
      vivinoCount: 8920,
      wineSearcher: 90,
      cellarTracker: 89,
    },
    prices: [
      {
        source: "rakuten",
        sourceName: "楽天市場",
        price: 2980,
        url: "#",
        lastUpdated: "2026-03-18",
        inStock: true,
      },
      {
        source: "amazon",
        sourceName: "Amazon.co.jp",
        price: 3200,
        url: "#",
        lastUpdated: "2026-03-18",
        inStock: true,
      },
    ],
    priceHistory: [
      { date: "2025-09", price: 2800, source: "rakuten" },
      { date: "2025-10", price: 2850, source: "rakuten" },
      { date: "2025-11", price: 2900, source: "rakuten" },
      { date: "2025-12", price: 2950, source: "rakuten" },
      { date: "2026-01", price: 2980, source: "rakuten" },
      { date: "2026-02", price: 2980, source: "rakuten" },
      { date: "2026-03", price: 2980, source: "rakuten" },
    ],
  },
  {
    id: "4",
    name: "Dom Pérignon 2015",
    nameJa: "ドン・ペリニヨン 2015",
    producer: "Moët & Chandon",
    region: "Champagne",
    country: "France",
    countryCode: "FR",
    vintage: 2015,
    type: "sparkling",
    grapeVarieties: ["シャルドネ", "ピノ・ノワール"],
    imageUrl: "/images/placeholder-wine.svg",
    description:
      "シャンパーニュの頂点。繊細な泡立ちと複雑な風味が長い余韻を残す。",
    ratings: {
      vivino: 4.4,
      vivinoCount: 6320,
      wineSearcher: 96,
      cellarTracker: 95,
    },
    prices: [
      {
        source: "rakuten",
        sourceName: "楽天市場",
        price: 28800,
        url: "#",
        lastUpdated: "2026-03-18",
        inStock: true,
      },
      {
        source: "amazon",
        sourceName: "Amazon.co.jp",
        price: 29800,
        url: "#",
        lastUpdated: "2026-03-18",
        inStock: true,
      },
    ],
    priceHistory: [
      { date: "2025-09", price: 26000, source: "rakuten" },
      { date: "2025-10", price: 26500, source: "rakuten" },
      { date: "2025-11", price: 27000, source: "rakuten" },
      { date: "2025-12", price: 28000, source: "rakuten" },
      { date: "2026-01", price: 28500, source: "rakuten" },
      { date: "2026-02", price: 28800, source: "rakuten" },
      { date: "2026-03", price: 28800, source: "rakuten" },
    ],
  },
  {
    id: "5",
    name: "Whispering Angel Rosé 2023",
    nameJa: "ウィスパリング・エンジェル ロゼ 2023",
    producer: "Château d'Esclans",
    region: "Provence",
    country: "France",
    countryCode: "FR",
    vintage: 2023,
    type: "rose",
    grapeVarieties: ["グルナッシュ", "サンソー", "ロール"],
    imageUrl: "/images/placeholder-wine.svg",
    description:
      "プロヴァンスロゼの代名詞。淡いサーモンピンクの色合いと繊細な果実味。",
    ratings: {
      vivino: 3.9,
      vivinoCount: 15200,
      wineSearcher: 88,
      cellarTracker: 87,
    },
    prices: [
      {
        source: "rakuten",
        sourceName: "楽天市場",
        price: 2480,
        url: "#",
        lastUpdated: "2026-03-18",
        inStock: true,
      },
    ],
    priceHistory: [
      { date: "2025-09", price: 2300, source: "rakuten" },
      { date: "2025-10", price: 2350, source: "rakuten" },
      { date: "2025-11", price: 2400, source: "rakuten" },
      { date: "2025-12", price: 2400, source: "rakuten" },
      { date: "2026-01", price: 2450, source: "rakuten" },
      { date: "2026-02", price: 2480, source: "rakuten" },
      { date: "2026-03", price: 2480, source: "rakuten" },
    ],
  },
  {
    id: "6",
    name: "Grace Wine Koshu 2022",
    nameJa: "グレイスワイン 甲州 2022",
    producer: "中央葡萄酒",
    region: "山梨県",
    country: "Japan",
    countryCode: "JP",
    vintage: 2022,
    type: "white",
    grapeVarieties: ["甲州"],
    imageUrl: "/images/placeholder-wine.svg",
    description:
      "日本固有品種「甲州」の魅力を最大限に引き出した一本。柑橘系の上品なアロマ。",
    ratings: {
      vivino: 3.7,
      vivinoCount: 890,
      wineSearcher: 89,
      cellarTracker: 88,
    },
    prices: [
      {
        source: "rakuten",
        sourceName: "楽天市場",
        price: 2200,
        url: "#",
        lastUpdated: "2026-03-18",
        inStock: true,
      },
    ],
    priceHistory: [
      { date: "2025-09", price: 2000, source: "rakuten" },
      { date: "2025-10", price: 2050, source: "rakuten" },
      { date: "2025-11", price: 2100, source: "rakuten" },
      { date: "2025-12", price: 2150, source: "rakuten" },
      { date: "2026-01", price: 2200, source: "rakuten" },
      { date: "2026-02", price: 2200, source: "rakuten" },
      { date: "2026-03", price: 2200, source: "rakuten" },
    ],
  },
  {
    id: "7",
    name: "Sassicaia 2019",
    nameJa: "サッシカイア 2019",
    producer: "Tenuta San Guido",
    region: "Bolgheri, Toscana",
    country: "Italy",
    countryCode: "IT",
    vintage: 2019,
    type: "red",
    grapeVarieties: ["カベルネ・ソーヴィニヨン", "カベルネ・フラン"],
    imageUrl: "/images/placeholder-wine.svg",
    description:
      "スーパートスカーナの元祖。凝縮した果実味と洗練されたタンニンのバランスが秀逸。",
    ratings: {
      vivino: 4.5,
      vivinoCount: 4560,
      wineSearcher: 96,
      cellarTracker: 95,
    },
    prices: [
      {
        source: "rakuten",
        sourceName: "楽天市場",
        price: 32800,
        url: "#",
        lastUpdated: "2026-03-18",
        inStock: true,
      },
      {
        source: "amazon",
        sourceName: "Amazon.co.jp",
        price: 34500,
        url: "#",
        lastUpdated: "2026-03-18",
        inStock: true,
      },
    ],
    priceHistory: [
      { date: "2025-09", price: 29000, source: "rakuten" },
      { date: "2025-10", price: 30000, source: "rakuten" },
      { date: "2025-11", price: 30500, source: "rakuten" },
      { date: "2025-12", price: 31000, source: "rakuten" },
      { date: "2026-01", price: 31500, source: "rakuten" },
      { date: "2026-02", price: 32000, source: "rakuten" },
      { date: "2026-03", price: 32800, source: "rakuten" },
    ],
  },
  {
    id: "8",
    name: "Penfolds Grange 2018",
    nameJa: "ペンフォールズ グランジ 2018",
    producer: "Penfolds",
    region: "South Australia",
    country: "Australia",
    countryCode: "AU",
    vintage: 2018,
    type: "red",
    grapeVarieties: ["シラーズ", "カベルネ・ソーヴィニヨン"],
    imageUrl: "/images/placeholder-wine.svg",
    description:
      "オーストラリアワインの最高峰。濃密な果実味と複雑なスパイス香が特徴。",
    ratings: {
      vivino: 4.5,
      vivinoCount: 1890,
      wineSearcher: 97,
      cellarTracker: 96,
    },
    prices: [
      {
        source: "rakuten",
        sourceName: "楽天市場",
        price: 98000,
        url: "#",
        lastUpdated: "2026-03-18",
        inStock: true,
      },
    ],
    priceHistory: [
      { date: "2025-09", price: 90000, source: "rakuten" },
      { date: "2025-10", price: 91000, source: "rakuten" },
      { date: "2025-11", price: 93000, source: "rakuten" },
      { date: "2025-12", price: 95000, source: "rakuten" },
      { date: "2026-01", price: 96000, source: "rakuten" },
      { date: "2026-02", price: 97000, source: "rakuten" },
      { date: "2026-03", price: 98000, source: "rakuten" },
    ],
  },
];

export const mockRegions: WineRegion[] = [
  {
    slug: "bordeaux",
    name: "Bordeaux",
    nameJa: "ボルドー",
    country: "France",
    countryCode: "FR",
    description:
      "世界最高峰のワイン産地。カベルネ・ソーヴィニヨンとメルローを中心とした赤ワインの聖地。",
    wineCount: 234,
    coordinates: [44.8378, -0.5792],
  },
  {
    slug: "burgundy",
    name: "Burgundy",
    nameJa: "ブルゴーニュ",
    country: "France",
    countryCode: "FR",
    description:
      "テロワールの概念を生んだ地。ピノ・ノワールとシャルドネの単一品種ワインで知られる。",
    wineCount: 189,
    coordinates: [47.0522, 4.3833],
  },
  {
    slug: "champagne",
    name: "Champagne",
    nameJa: "シャンパーニュ",
    country: "France",
    countryCode: "FR",
    description: "スパークリングワインの最高峰。伝統的製法で造られる華やかな泡。",
    wineCount: 145,
    coordinates: [49.0469, 3.9536],
  },
  {
    slug: "tuscany",
    name: "Tuscany",
    nameJa: "トスカーナ",
    country: "Italy",
    countryCode: "IT",
    description:
      "キャンティからスーパートスカーナまで。サンジョヴェーゼを中心とした多彩なワイン。",
    wineCount: 167,
    coordinates: [43.3714, 11.1224],
  },
  {
    slug: "piedmont",
    name: "Piedmont",
    nameJa: "ピエモンテ",
    country: "Italy",
    countryCode: "IT",
    description:
      "バローロとバルバレスコの故郷。ネッビオーロから生まれる長期熟成型の偉大な赤。",
    wineCount: 123,
    coordinates: [44.6997, 8.0354],
  },
  {
    slug: "napa-valley",
    name: "Napa Valley",
    nameJa: "ナパ・ヴァレー",
    country: "USA",
    countryCode: "US",
    description:
      "カリフォルニアの最高級ワイン産地。力強いカベルネ・ソーヴィニヨンが世界的に評価。",
    wineCount: 98,
    coordinates: [38.5025, -122.2654],
  },
  {
    slug: "yamanashi",
    name: "Yamanashi",
    nameJa: "山梨県",
    country: "Japan",
    countryCode: "JP",
    description:
      "日本ワイン発祥の地。甲州やマスカット・ベーリーAなど固有品種の魅力を発信。",
    wineCount: 56,
    coordinates: [35.6642, 138.5681],
  },
  {
    slug: "marlborough",
    name: "Marlborough",
    nameJa: "マールボロ",
    country: "New Zealand",
    countryCode: "NZ",
    description:
      "ソーヴィニヨン・ブランの新天地。鮮烈なアロマと爽やかな酸味が特徴。",
    wineCount: 67,
    coordinates: [-41.5134, 173.9612],
  },
  {
    slug: "barossa-valley",
    name: "Barossa Valley",
    nameJa: "バロッサ・ヴァレー",
    country: "Australia",
    countryCode: "AU",
    description:
      "オーストラリアを代表するシラーズの産地。濃厚でパワフルなスタイル。",
    wineCount: 78,
    coordinates: [-34.5612, 138.9536],
  },
  {
    slug: "rioja",
    name: "Rioja",
    nameJa: "リオハ",
    country: "Spain",
    countryCode: "ES",
    description:
      "スペイン最高の赤ワイン産地。テンプラニーリョから造る伝統的な熟成ワイン。",
    wineCount: 89,
    coordinates: [42.4658, -2.4450],
  },
  {
    slug: "provence",
    name: "Provence",
    nameJa: "プロヴァンス",
    country: "France",
    countryCode: "FR",
    description: "世界最高のロゼワイン産地。地中海の風を感じる淡い色合いと繊細な味わい。",
    wineCount: 45,
    coordinates: [43.5298, 5.4474],
  },
];

export const mockTweets: Tweet[] = [
  {
    id: "t1",
    authorName: "ワインソムリエ田中",
    authorHandle: "@wine_tanaka",
    authorAvatar: "",
    content:
      "今日のおすすめは甲州ワイン！ グレイスワインの甲州2022は和食との相性が抜群。特に刺身との組み合わせは最高です。日本ワインの実力を再認識。 #日本ワイン #甲州 #ワイン",
    createdAt: "2026-03-18T10:30:00Z",
    likes: 234,
    retweets: 45,
    wineRelated: ["甲州", "日本ワイン", "グレイスワイン"],
  },
  {
    id: "t2",
    authorName: "Wine Explorer JP",
    authorHandle: "@wine_explorer_jp",
    authorAvatar: "",
    content:
      "オーパスワン2019、楽天で52,800円まで下がってますね。半年前より4,000円安い。今が買い時かも？ #OpusOne #ナパバレー #ワイン投資",
    createdAt: "2026-03-18T09:15:00Z",
    likes: 567,
    retweets: 123,
    wineRelated: ["オーパスワン", "ナパバレー"],
  },
  {
    id: "t3",
    authorName: "プロヴァンスロゼ愛好会",
    authorHandle: "@provence_rose",
    authorAvatar: "",
    content:
      "春が近づくとロゼワインが恋しくなる季節。ウィスパリング・エンジェルは2,480円でこのクオリティ。花見のお供に最適！ #ロゼワイン #プロヴァンス #花見",
    createdAt: "2026-03-17T18:45:00Z",
    likes: 345,
    retweets: 67,
    wineRelated: ["ロゼ", "プロヴァンス", "ウィスパリング・エンジェル"],
  },
  {
    id: "t4",
    authorName: "イタリアワイン通信",
    authorHandle: "@italia_vino",
    authorAvatar: "",
    content:
      "サッシカイア2019がWine Searcherで96点！ スーパートスカーナの中でも頭一つ抜けた存在。ボルゲリの気候が2019ヴィンテージに最高の恵みをもたらした。 #Sassicaia #SuperTuscan #イタリアワイン",
    createdAt: "2026-03-17T14:20:00Z",
    likes: 456,
    retweets: 89,
    wineRelated: ["サッシカイア", "トスカーナ", "イタリアワイン"],
  },
  {
    id: "t5",
    authorName: "シャンパーニュ専門家",
    authorHandle: "@champagne_expert",
    authorAvatar: "",
    content:
      "ドン・ペリニヨン2015の熟成が素晴らしい段階に入ってきた。今開けても美味しいが、あと5年待てばさらに化ける。セラーに余裕があるなら絶対にキープすべき。 #DomPerignon #シャンパーニュ",
    createdAt: "2026-03-16T20:00:00Z",
    likes: 678,
    retweets: 156,
    wineRelated: ["ドン・ペリニヨン", "シャンパーニュ"],
  },
];

export const mockTrends: TrendItem[] = [
  { keyword: "#日本ワイン", count: 1245, change: 15, wines: ["甲州", "マスカット・ベーリーA"] },
  { keyword: "#ナチュラルワイン", count: 987, change: 23, wines: ["自然派", "オーガニック"] },
  { keyword: "#ボルドー2018", count: 756, change: -5, wines: ["マルゴー", "ラフィット"] },
  { keyword: "#花見ワイン", count: 623, change: 45, wines: ["ロゼ", "スパークリング"] },
  { keyword: "#ワイン投資", count: 534, change: 8, wines: ["ブルゴーニュ", "ボルドー"] },
];
