import type { Wine } from "@/types/wine";

export const mockWines: Wine[] = [
  // ===== 赤ワイン =====
  {
    id: "1",
    name: "Casillero del Diablo Cabernet Sauvignon",
    nameJa: "カッシェロ・デル・ディアブロ カベルネ・ソーヴィニヨン",
    producer: "Concha y Toro",
    country: "Chile",
    countryCode: "CL",
    type: "red",
    grapeVarieties: ["カベルネ・ソーヴィニヨン"],
    description:
      "コンビニで買える本格チリ赤。しっかりした果実味とまろやかなタンニンで、肉料理にぴったり。",
    price: 698,
    stores: [
      { type: "seven", name: "セブン-イレブン", price: 698, inStock: true },
      { type: "lawson", name: "ローソン", price: 698, inStock: true },
      { type: "aeon", name: "イオン", price: 658, inStock: true },
      { type: "amazon", name: "Amazon", price: 645, inStock: true },
    ],
    buzzScore: 72,
    vivinoScore: 3.7,
    costPerformance: 88,
    tags: ["家飲み", "肉料理", "コンビニ"],
    posts: [
      { id: "p1-1", platform: "x", authorName: "ワイン初心者OL", authorHandle: "@wine_ollife", content: "セブンで買ったカッシェロ・デル・ディアブロ、698円なのに普通にうまい…！肉じゃがと合わせたら最高でした", likes: 342, postedAt: "2026-03-18" },
      { id: "p1-2", platform: "instagram", authorName: "おうちワイン部", authorHandle: "@ouchi_wine", content: "今夜のお供はディアブロ赤🍷 コンビニワインの域を超えてる。ステーキにぴったり！", likes: 891, postedAt: "2026-03-15" },
    ],
  },
  {
    id: "2",
    name: "Frontera Cabernet Sauvignon",
    nameJa: "フロンテラ カベルネ・ソーヴィニヨン",
    producer: "Concha y Toro",
    country: "Chile",
    countryCode: "CL",
    type: "red",
    grapeVarieties: ["カベルネ・ソーヴィニヨン"],
    description:
      "ワンコインで買える驚きのコスパ。軽やかだけど果実味しっかり。デイリーワインの定番。",
    price: 498,
    stores: [
      { type: "seven", name: "セブン-イレブン", price: 498, inStock: true },
      { type: "familymart", name: "ファミリーマート", price: 498, inStock: true },
      { type: "donki", name: "ドン・キホーテ", price: 458, inStock: true },
    ],
    buzzScore: 58,
    vivinoScore: 3.4,
    costPerformance: 92,
    tags: ["家飲み", "ワンコイン", "コンビニ"],
    posts: [
      { id: "p2-1", platform: "x", authorName: "節約ワイン道", authorHandle: "@setsuyaku_wine", content: "フロンテラ498円、マジでワンコイン最強説。味はちゃんとカベルネしてる", likes: 215, postedAt: "2026-03-17" },
    ],
  },
  {
    id: "3",
    name: "Montepulciano d'Abruzzo",
    nameJa: "モンテプルチアーノ・ダブルッツォ",
    producer: "Citra",
    country: "Italy",
    countryCode: "IT",
    type: "red",
    grapeVarieties: ["モンテプルチアーノ"],
    description:
      "イタリアの太陽を感じる果実味。渋みが穏やかで飲みやすく、パスタやピザとの相性抜群。",
    price: 598,
    stores: [
      { type: "kaldi", name: "カルディ", price: 598, inStock: true },
      { type: "aeon", name: "イオン", price: 578, inStock: true },
      { type: "rakuten", name: "楽天市場", price: 548, inStock: true },
    ],
    buzzScore: 65,
    vivinoScore: 3.6,
    costPerformance: 90,
    tags: ["家飲み", "イタリアン", "パスタ"],
    posts: [
      { id: "p3-1", platform: "x", authorName: "パスタとワイン", authorHandle: "@pasta_vino", content: "カルディで見つけたモンテプルチアーノ598円。ボロネーゼと合わせたら幸せすぎた", likes: 178, postedAt: "2026-03-16" },
    ],
  },
  {
    id: "4",
    name: "Côtes du Rhône Rouge",
    nameJa: "コート・デュ・ローヌ ルージュ",
    producer: "E. Guigal",
    country: "France",
    countryCode: "FR",
    type: "red",
    grapeVarieties: ["グルナッシュ", "シラー", "ムールヴェードル"],
    description:
      "フランスワインなのにこの価格。スパイシーで深い味わい。1,000円台で本格ローヌが楽しめる。",
    price: 1380,
    stores: [
      { type: "kaldi", name: "カルディ", price: 1380, inStock: true },
      { type: "seijoishii", name: "成城石井", price: 1480, inStock: true },
      { type: "amazon", name: "Amazon", price: 1280, inStock: true },
    ],
    buzzScore: 78,
    vivinoScore: 3.8,
    costPerformance: 85,
    tags: ["手土産", "フランス", "本格派"],
    posts: [
      { id: "p4-1", platform: "x", authorName: "ソムリエ見習い", authorHandle: "@somme_trainee", content: "ギガルのコート・デュ・ローヌが1,380円って信じられる？フランスワインの底力を感じる", likes: 523, postedAt: "2026-03-18" },
      { id: "p4-2", platform: "instagram", authorName: "ワインと料理", authorHandle: "@wine_cuisine", content: "カルディで買えるフランスワイン🇫🇷 ローヌの赤、ビーフシチューと最高の組み合わせ", likes: 1205, postedAt: "2026-03-14" },
    ],
  },
  {
    id: "5",
    name: "Casillero del Diablo Pinot Noir",
    nameJa: "カッシェロ・デル・ディアブロ ピノ・ノワール",
    producer: "Concha y Toro",
    country: "Chile",
    countryCode: "CL",
    type: "red",
    grapeVarieties: ["ピノ・ノワール"],
    description:
      "千円以下でピノ・ノワールが飲める幸せ。チェリーやラズベリーの華やかな香り、和食にも合う。",
    price: 698,
    stores: [
      { type: "seven", name: "セブン-イレブン", price: 698, inStock: true },
      { type: "lawson", name: "ローソン", price: 698, inStock: true },
      { type: "amazon", name: "Amazon", price: 645, inStock: true },
    ],
    buzzScore: 68,
    vivinoScore: 3.5,
    costPerformance: 86,
    tags: ["家飲み", "和食", "コンビニ"],
    posts: [
      { id: "p5-1", platform: "x", authorName: "和食ワインペアリング", authorHandle: "@washoku_wine", content: "ディアブロのピノ・ノワール、筑前煮と合わせたら意外とイケる。698円で和食ペアリング楽しめるの最高", likes: 287, postedAt: "2026-03-17" },
    ],
  },

  // ===== 白ワイン =====
  {
    id: "6",
    name: "Casillero del Diablo Chardonnay",
    nameJa: "カッシェロ・デル・ディアブロ シャルドネ",
    producer: "Concha y Toro",
    country: "Chile",
    countryCode: "CL",
    type: "white",
    grapeVarieties: ["シャルドネ"],
    description:
      "トロピカルフルーツとほのかな樽香。コンビニ白ワインの王者。魚料理からチキンまで万能。",
    price: 698,
    stores: [
      { type: "seven", name: "セブン-イレブン", price: 698, inStock: true },
      { type: "lawson", name: "ローソン", price: 698, inStock: true },
      { type: "familymart", name: "ファミリーマート", price: 698, inStock: true },
      { type: "amazon", name: "Amazon", price: 645, inStock: true },
    ],
    buzzScore: 82,
    vivinoScore: 3.6,
    costPerformance: 89,
    tags: ["家飲み", "魚料理", "コンビニ", "万能"],
    posts: [
      { id: "p6-1", platform: "x", authorName: "コンビニワイン研究家", authorHandle: "@cvs_wine", content: "ディアブロのシャルドネ、全コンビニ白ワインの中でダントツ1位だと思う。698円でこの樽香はすごい", likes: 645, postedAt: "2026-03-19" },
      { id: "p6-2", platform: "instagram", authorName: "晩酌タイム", authorHandle: "@banshaku_time", content: "今日はセブンのディアブロ白🥂 お刺身と一緒に。トロピカルな香りが最高〜", likes: 432, postedAt: "2026-03-16" },
    ],
  },
  {
    id: "7",
    name: "Santa Rita 120 Sauvignon Blanc",
    nameJa: "サンタ・リタ 120 ソーヴィニヨン・ブラン",
    producer: "Santa Rita",
    country: "Chile",
    countryCode: "CL",
    type: "white",
    grapeVarieties: ["ソーヴィニヨン・ブラン"],
    description:
      "柑橘系の爽やかアロマ。キリッとした酸味がサラダや刺身と最高のマリアージュ。",
    price: 550,
    stores: [
      { type: "aeon", name: "イオン", price: 550, inStock: true },
      { type: "donki", name: "ドン・キホーテ", price: 528, inStock: true },
      { type: "rakuten", name: "楽天市場", price: 498, inStock: true },
    ],
    buzzScore: 55,
    vivinoScore: 3.5,
    costPerformance: 91,
    tags: ["家飲み", "刺身", "ワンコイン"],
    posts: [
      { id: "p7-1", platform: "x", authorName: "デイリーワイン派", authorHandle: "@daily_wine", content: "サンタ・リタ120のソーヴィニヨン・ブラン、500円台で買えるのにちゃんと爽やか。刺身の日はこれ", likes: 156, postedAt: "2026-03-15" },
    ],
  },
  {
    id: "8",
    name: "Bogle Chardonnay",
    nameJa: "ボーグル シャルドネ",
    producer: "Bogle Vineyards",
    country: "USA",
    countryCode: "US",
    type: "white",
    grapeVarieties: ["シャルドネ"],
    description:
      "カリフォルニアの太陽を詰め込んだリッチな白。バター感とバニラ香が心地よく、SNSで大人気。",
    price: 1580,
    stores: [
      { type: "costco", name: "コストコ", price: 1298, inStock: true },
      { type: "seijoishii", name: "成城石井", price: 1580, inStock: true },
      { type: "amazon", name: "Amazon", price: 1480, inStock: true },
    ],
    buzzScore: 91,
    vivinoScore: 4.0,
    costPerformance: 87,
    tags: ["SNS話題", "手土産", "リッチ"],
    posts: [
      { id: "p8-1", platform: "x", authorName: "ワイン沼にハマった人", authorHandle: "@wine_numa", content: "ボーグルのシャルドネ飲んだら人生変わった。コストコで1,298円。この価格でカリフォルニアのリッチ白が飲めるの反則", likes: 1893, postedAt: "2026-03-19" },
      { id: "p8-2", platform: "instagram", authorName: "コストコワイン部", authorHandle: "@costco_wine_bu", content: "コストコで見つけたボーグル🍾 バターとバニラの香りがたまらない。1,298円は即買い！", likes: 2341, postedAt: "2026-03-17" },
      { id: "p8-3", platform: "x", authorName: "成城石井マニア", authorHandle: "@seijo_mania", content: "成城石井でボーグルシャルドネ買った。SNSで話題になってるだけある。リッチなのにスイスイ飲める", likes: 567, postedAt: "2026-03-14" },
    ],
  },
  {
    id: "9",
    name: "Torrontés",
    nameJa: "トロンテス",
    producer: "Colomé",
    country: "Argentina",
    countryCode: "AR",
    type: "white",
    grapeVarieties: ["トロンテス"],
    description:
      "マスカットのようなアロマティックな香り。華やかだけどドライで食事に合う。知る人ぞ知る逸品。",
    price: 1280,
    stores: [
      { type: "kaldi", name: "カルディ", price: 1280, inStock: true },
      { type: "liquor_shop", name: "やまや", price: 1180, inStock: true },
      { type: "rakuten", name: "楽天市場", price: 1150, inStock: true },
    ],
    buzzScore: 61,
    vivinoScore: 3.8,
    costPerformance: 84,
    tags: ["アロマティック", "新発見", "エスニック"],
    posts: [
      { id: "p9-1", platform: "x", authorName: "隠れ名品ハンター", authorHandle: "@kakure_meihin", content: "トロンテスっていう品種知ってる？マスカットみたいな香りなのに辛口。エスニック料理に合う！カルディにあるよ", likes: 312, postedAt: "2026-03-16" },
    ],
  },
  {
    id: "10",
    name: "Cloudy Bay Sauvignon Blanc",
    nameJa: "クラウディー・ベイ ソーヴィニヨン・ブラン",
    producer: "Cloudy Bay",
    country: "New Zealand",
    countryCode: "NZ",
    type: "white",
    grapeVarieties: ["ソーヴィニヨン・ブラン"],
    description:
      "NZソーヴィニヨン・ブランの代名詞。パッションフルーツとハーブの爽快感。奮発する日に。",
    price: 2980,
    stores: [
      { type: "seijoishii", name: "成城石井", price: 2980, inStock: true },
      { type: "amazon", name: "Amazon", price: 2780, inStock: true },
      { type: "rakuten", name: "楽天市場", price: 2680, inStock: true },
    ],
    buzzScore: 85,
    vivinoScore: 4.0,
    costPerformance: 75,
    tags: ["ご褒美", "手土産", "定番"],
    posts: [
      { id: "p10-1", platform: "x", authorName: "ワインレビュアー", authorHandle: "@wine_reviewer", content: "クラウディー・ベイは別格。NZソーヴィニヨン・ブランの教科書的存在。手土産に持っていくと必ず喜ばれる", likes: 876, postedAt: "2026-03-18" },
      { id: "p10-2", platform: "instagram", authorName: "ご褒美ワイン", authorHandle: "@gohoubi_wine", content: "金曜のご褒美にクラウディー・ベイ🥂 パッションフルーツの香りが最高すぎる", likes: 1543, postedAt: "2026-03-14" },
    ],
  },

  // ===== ロゼ =====
  {
    id: "11",
    name: "Mateus Rosé",
    nameJa: "マテウス ロゼ",
    producer: "Sogrape",
    country: "Portugal",
    countryCode: "PT",
    type: "rose",
    grapeVarieties: ["バガ", "ルフェテ", "トゥリガ・ナシオナル"],
    description:
      "世界で最も売れているロゼワイン。微発泡でフルーティ。ピクニックやBBQの定番。",
    price: 780,
    stores: [
      { type: "aeon", name: "イオン", price: 780, inStock: true },
      { type: "kaldi", name: "カルディ", price: 820, inStock: true },
      { type: "amazon", name: "Amazon", price: 698, inStock: true },
    ],
    buzzScore: 63,
    vivinoScore: 3.4,
    costPerformance: 83,
    tags: ["BBQ", "ピクニック", "微発泡"],
    posts: [
      { id: "p11-1", platform: "x", authorName: "ピクニック好き", authorHandle: "@picnic_love", content: "マテウスロゼ持ってBBQしてきた！微発泡で飲みやすいし780円だし、アウトドアワインの正解", likes: 234, postedAt: "2026-03-15" },
    ],
  },
  {
    id: "12",
    name: "Whispering Angel Rosé",
    nameJa: "ウィスパリング・エンジェル ロゼ",
    producer: "Château d'Esclans",
    country: "France",
    countryCode: "FR",
    type: "rose",
    grapeVarieties: ["グルナッシュ", "サンソー", "ロール"],
    description:
      "インスタ映えNo.1ロゼ。淡いサーモンピンクの美しさと繊細な味わい。パーティの主役に。",
    price: 2480,
    stores: [
      { type: "seijoishii", name: "成城石井", price: 2480, inStock: true },
      { type: "amazon", name: "Amazon", price: 2280, inStock: true },
      { type: "rakuten", name: "楽天市場", price: 2180, inStock: true },
    ],
    buzzScore: 94,
    vivinoScore: 3.9,
    costPerformance: 72,
    tags: ["SNS話題", "パーティ", "おしゃれ", "ご褒美"],
    posts: [
      { id: "p12-1", platform: "instagram", authorName: "映えワイン", authorHandle: "@bae_wine", content: "ウィスパリング・エンジェル💕 このサーモンピンクの美しさよ…味も繊細で最高。パーティの主役", likes: 3421, postedAt: "2026-03-19" },
      { id: "p12-2", platform: "x", authorName: "ロゼ専門家", authorHandle: "@rose_expert", content: "ウィスパリングエンジェル、インスタで見ない日がないくらいバズってる。実際飲んでも美味しいからすごい", likes: 1234, postedAt: "2026-03-17" },
      { id: "p12-3", platform: "instagram", authorName: "おしゃれワイン会", authorHandle: "@oshare_wine", content: "女子会にウィスパリング・エンジェル🌸 見た目も味も完璧なロゼ！", likes: 2876, postedAt: "2026-03-13" },
    ],
  },

  // ===== スパークリング =====
  {
    id: "13",
    name: "Freixenet Cordon Negro Brut",
    nameJa: "フレシネ コルドン・ネグロ ブリュット",
    producer: "Freixenet",
    country: "Spain",
    countryCode: "ES",
    type: "sparkling",
    grapeVarieties: ["マカベオ", "パレリャーダ", "チャレッロ"],
    description:
      "コンビニで買える本格カヴァ。黒ボトルがかっこいい。辛口で食事にも合う万能スパークリング。",
    price: 1098,
    stores: [
      { type: "seven", name: "セブン-イレブン", price: 1098, inStock: true },
      { type: "lawson", name: "ローソン", price: 1098, inStock: true },
      { type: "aeon", name: "イオン", price: 998, inStock: true },
      { type: "amazon", name: "Amazon", price: 928, inStock: true },
    ],
    buzzScore: 76,
    vivinoScore: 3.6,
    costPerformance: 88,
    tags: ["パーティ", "コンビニ", "乾杯"],
    posts: [
      { id: "p13-1", platform: "x", authorName: "泡好き", authorHandle: "@awa_suki", content: "フレシネの黒ボトルかっこよすぎ。コンビニで1,098円で本格カヴァ買えるの知らない人多すぎ", likes: 456, postedAt: "2026-03-18" },
      { id: "p13-2", platform: "instagram", authorName: "乾杯ワイン", authorHandle: "@kanpai_wine", content: "今夜はフレシネで乾杯🥂 黒ボトルが映える！辛口で食事にも合う万能泡", likes: 789, postedAt: "2026-03-15" },
    ],
  },
  {
    id: "14",
    name: "Martini Asti Spumante",
    nameJa: "マルティーニ アスティ・スプマンテ",
    producer: "Martini & Rossi",
    country: "Italy",
    countryCode: "IT",
    type: "sparkling",
    grapeVarieties: ["モスカート"],
    description:
      "マスカットの甘い香り。甘口だけど重くない。ワイン初心者やスイーツとのペアリングに最適。",
    price: 1280,
    stores: [
      { type: "aeon", name: "イオン", price: 1280, inStock: true },
      { type: "donki", name: "ドン・キホーテ", price: 1180, inStock: true },
      { type: "amazon", name: "Amazon", price: 1098, inStock: true },
    ],
    buzzScore: 70,
    vivinoScore: 3.7,
    costPerformance: 82,
    tags: ["初心者", "スイーツ", "女子会"],
    posts: [
      { id: "p14-1", platform: "x", authorName: "ワイン初心者", authorHandle: "@wine_beginner", content: "マルティーニのアスティ、甘くて飲みやすい！ワイン苦手な友達もこれは美味しいって言ってた", likes: 345, postedAt: "2026-03-16" },
    ],
  },
  {
    id: "15",
    name: "Chandon Brut",
    nameJa: "シャンドン ブリュット",
    producer: "Domaine Chandon",
    country: "Australia",
    countryCode: "AU",
    type: "sparkling",
    grapeVarieties: ["シャルドネ", "ピノ・ノワール"],
    description:
      "モエ系列のプレミアム泡。シャンパンに迫るクオリティで半額以下。記念日やお祝いに。",
    price: 1980,
    stores: [
      { type: "seijoishii", name: "成城石井", price: 1980, inStock: true },
      { type: "costco", name: "コストコ", price: 1680, inStock: true },
      { type: "amazon", name: "Amazon", price: 1780, inStock: true },
    ],
    buzzScore: 83,
    vivinoScore: 3.9,
    costPerformance: 86,
    tags: ["記念日", "手土産", "プレミアム"],
    posts: [
      { id: "p15-1", platform: "x", authorName: "シャンパン代わりに", authorHandle: "@champagne_alt", content: "シャンドン、モエ系列なのに1,980円。シャンパンの半額以下でこのクオリティは反則。記念日に使える", likes: 987, postedAt: "2026-03-18" },
      { id: "p15-2", platform: "instagram", authorName: "お祝いワイン", authorHandle: "@oiwai_wine", content: "誕生日にシャンドンで乾杯🎂 2,000円以下とは思えない華やかさ！", likes: 1567, postedAt: "2026-03-12" },
    ],
  },
  {
    id: "16",
    name: "Codorníu Clásico Seco",
    nameJa: "コドーニュ クラシコ セコ",
    producer: "Codorníu",
    country: "Spain",
    countryCode: "ES",
    type: "sparkling",
    grapeVarieties: ["マカベオ", "チャレッロ", "パレリャーダ"],
    description:
      "世界最古のカヴァ生産者。キレのある辛口泡が500円台。普段の食卓にシュワッと贅沢を。",
    price: 598,
    stores: [
      { type: "donki", name: "ドン・キホーテ", price: 598, inStock: true },
      { type: "aeon", name: "イオン", price: 628, inStock: true },
      { type: "rakuten", name: "楽天市場", price: 548, inStock: true },
    ],
    buzzScore: 52,
    vivinoScore: 3.4,
    costPerformance: 93,
    tags: ["ワンコイン", "家飲み", "コスパ最強"],
    posts: [
      { id: "p16-1", platform: "x", authorName: "コスパ番長", authorHandle: "@cospa_bancho", content: "コドーニュのカヴァ、ドンキで598円。500円台のスパークリングで一番うまいと思う", likes: 198, postedAt: "2026-03-14" },
    ],
  },

  // ===== ちょっと贅沢（〜5,000円） =====
  {
    id: "17",
    name: "Louis Jadot Bourgogne Chardonnay",
    nameJa: "ルイ・ジャド ブルゴーニュ シャルドネ",
    producer: "Louis Jadot",
    country: "France",
    countryCode: "FR",
    type: "white",
    grapeVarieties: ["シャルドネ"],
    description:
      "本場ブルゴーニュの白がこの価格。上品なミネラル感と果実味のバランス。ワンランク上の食卓に。",
    price: 2480,
    stores: [
      { type: "seijoishii", name: "成城石井", price: 2480, inStock: true },
      { type: "liquor_shop", name: "やまや", price: 2380, inStock: true },
      { type: "amazon", name: "Amazon", price: 2200, inStock: true },
    ],
    buzzScore: 74,
    vivinoScore: 3.8,
    costPerformance: 80,
    tags: ["手土産", "ブルゴーニュ", "ご褒美"],
    posts: [
      { id: "p17-1", platform: "x", authorName: "ブルゴーニュ入門", authorHandle: "@bourgogne_101", content: "ルイ・ジャドのブルゴーニュシャルドネ、2,480円でブルゴーニュ体験できるの最高。ミネラル感がたまらん", likes: 432, postedAt: "2026-03-17" },
    ],
  },
  {
    id: "18",
    name: "Oyster Bay Pinot Noir",
    nameJa: "オイスター・ベイ ピノ・ノワール",
    producer: "Oyster Bay",
    country: "New Zealand",
    countryCode: "NZ",
    type: "red",
    grapeVarieties: ["ピノ・ノワール"],
    description:
      "NZ産ピノの実力。チェリーとスパイスの絶妙バランス。鶏肉やサーモンとの相性が神。",
    price: 1980,
    stores: [
      { type: "seijoishii", name: "成城石井", price: 1980, inStock: true },
      { type: "kaldi", name: "カルディ", price: 1980, inStock: true },
      { type: "amazon", name: "Amazon", price: 1780, inStock: true },
    ],
    buzzScore: 80,
    vivinoScore: 3.9,
    costPerformance: 83,
    tags: ["SNS話題", "鶏肉", "サーモン"],
    posts: [
      { id: "p18-1", platform: "x", authorName: "NZワイン推し", authorHandle: "@nz_wine_oshi", content: "オイスター・ベイのピノ、サーモンのムニエルと合わせたら天国だった。成城石井で1,980円", likes: 678, postedAt: "2026-03-19" },
      { id: "p18-2", platform: "instagram", authorName: "ワインペアリング研究", authorHandle: "@pairing_lab", content: "オイスター・ベイ ピノ・ノワール🍷 鶏の照り焼きとの相性が神すぎた！", likes: 1123, postedAt: "2026-03-15" },
    ],
  },
  {
    id: "19",
    name: "Mionetto Prosecco Brut",
    nameJa: "ミオネット プロセッコ ブリュット",
    producer: "Mionetto",
    country: "Italy",
    countryCode: "IT",
    type: "sparkling",
    grapeVarieties: ["グレーラ"],
    description:
      "イタリアのプロセッコ人気を牽引。フルーティで飲みやすい泡。アペロール・スプリッツにも。",
    price: 1580,
    stores: [
      { type: "kaldi", name: "カルディ", price: 1580, inStock: true },
      { type: "costco", name: "コストコ", price: 1380, inStock: true },
      { type: "amazon", name: "Amazon", price: 1450, inStock: true },
    ],
    buzzScore: 87,
    vivinoScore: 3.8,
    costPerformance: 84,
    tags: ["SNS話題", "アペロール", "パーティ"],
    posts: [
      { id: "p19-1", platform: "instagram", authorName: "アペロールスプリッツ部", authorHandle: "@aperol_bu", content: "ミオネットのプロセッコでアペロール・スプリッツ作った🍹 カルディで1,580円！おうちバー最高", likes: 2156, postedAt: "2026-03-18" },
      { id: "p19-2", platform: "x", authorName: "プロセッコ推し", authorHandle: "@prosecco_love", content: "ミオネットのプロセッコ、フルーティで飲みやすい。コストコで1,380円はお買い得すぎ", likes: 789, postedAt: "2026-03-16" },
    ],
  },
  {
    id: "20",
    name: "Familia Zuccardi Serie A Malbec",
    nameJa: "ズッカルディ セリエA マルベック",
    producer: "Familia Zuccardi",
    country: "Argentina",
    countryCode: "AR",
    type: "red",
    grapeVarieties: ["マルベック"],
    description:
      "アルゼンチンの星。濃厚な果実味とスモーキーな余韻。BBQやステーキに合わせたい。",
    price: 1480,
    stores: [
      { type: "kaldi", name: "カルディ", price: 1480, inStock: true },
      { type: "liquor_shop", name: "やまや", price: 1380, inStock: true },
      { type: "rakuten", name: "楽天市場", price: 1280, inStock: true },
    ],
    buzzScore: 73,
    vivinoScore: 3.9,
    costPerformance: 86,
    tags: ["BBQ", "ステーキ", "濃厚"],
    posts: [
      { id: "p20-1", platform: "x", authorName: "肉とワイン", authorHandle: "@niku_wine", content: "ズッカルディのマルベック、BBQに合わせたら最高すぎた。濃厚な果実味とスモーキーさがステーキに寄り添う", likes: 543, postedAt: "2026-03-17" },
    ],
  },
];

/** 店舗名のラベル */
export const storeLabels: Record<string, string> = {
  seven: "セブン",
  lawson: "ローソン",
  familymart: "ファミマ",
  aeon: "イオン",
  seijoishii: "成城石井",
  kaldi: "カルディ",
  donki: "ドンキ",
  costco: "コストコ",
  rakuten: "楽天",
  amazon: "Amazon",
  liquor_shop: "酒屋",
};
