import type { Wine } from "@/types/wine";

export const mockWines: Wine[] = [
  // ===== 赤ワイン =====
  {
    id: "1",
    name: "Casillero del Diablo Cabernet Sauvignon",
    nameJa: "カッシェロ・デル・ディアブロ カベルネ・ソーヴィニヨン",
    producer: "Concha y Toro",
    country: "Chile",
    countryCode: "CL",
    type: "red",
    grapeVarieties: ["カベルネ・ソーヴィニヨン"],
    description:
      "コンビニで買える本格チリ赤。しっかりした果実味とまろやかなタンニンで、肉料理にぴったり。",
    price: 698,
    stores: [
      { type: "seven", name: "セブン-イレブン", price: 698, inStock: true },
      { type: "lawson", name: "ローソン", price: 698, inStock: true },
      { type: "aeon", name: "イオン", price: 658, inStock: true },
      { type: "amazon", name: "Amazon", price: 645, inStock: true },
    ],
    buzzScore: 85,
    vivinoScore: 3.7,
    costPerformance: 88,
    tags: ["家飲み", "肉料理", "コンビニ"],
    tweetUrls: ["https://x.com/the_wild_hunt/status/2034357346185683379", "https://x.com/nagakushinozomi/status/2032399271031701696"],
    abv: 13.5,
    servingTemp: "16-18℃",
    pairings: ["ステーキ", "ハンバーグ", "肉じゃが"],
    whyBuyNow: "コンビニ赤の王者。698円で本格チリカベルネが飲める奇跡",
    buyLinks: [{ store: "Amazon", url: "https://www.amazon.co.jp/s?k=カッシェロデルディアブロ+カベルネソーヴィニヨン", price: 645 }, { store: "楽天", url: "https://search.rakuten.co.jp/search/mall/カッシェロデルディアブロ+カベルネ/", price: 658 }],
  },
  {
    id: "2",
    name: "Frontera Cabernet Sauvignon",
    nameJa: "フロンテラ カベルネ・ソーヴィニヨン",
    producer: "Concha y Toro",
    country: "Chile",
    countryCode: "CL",
    type: "red",
    grapeVarieties: ["カベルネ・ソーヴィニヨン"],
    description:
      "ワンコインで買える驚きのコスパ。軽やかだけど果実味しっかり。デイリーワインの定番。",
    price: 498,
    stores: [
      { type: "seven", name: "セブン-イレブン", price: 498, inStock: true },
      { type: "familymart", name: "ファミリーマート", price: 498, inStock: true },
      { type: "donki", name: "ドン・キホーテ", price: 458, inStock: true },
    ],
    buzzScore: 70,
    vivinoScore: 3.3,
    costPerformance: 92,
    tags: ["家飲み", "ワンコイン", "コンビニ"],
    tweetUrls: ["https://x.com/winenomuhito/status/2034035261160722440"],
    abv: 12.0,
    servingTemp: "16-18℃",
    pairings: ["パスタ", "ピザ", "焼き鳥"],
    whyBuyNow: "498円のワンコイン赤。デイリーワインの最適解",
    buyLinks: [{ store: "Amazon", url: "https://www.amazon.co.jp/s?k=フロンテラ+カベルネソーヴィニヨン", price: 458 }],
  },
  {
    id: "3",
    name: "Montepulciano d'Abruzzo",
    nameJa: "モンテプルチアーノ・ダブルッツォ",
    producer: "Citra",
    country: "Italy",
    countryCode: "IT",
    type: "red",
    grapeVarieties: ["モンテプルチアーノ"],
    description:
      "イタリアの太陽を感じる果実味。渋みが穏やかで飲みやすく、パスタやピザとの相性抜群。",
    price: 598,
    stores: [
      { type: "kaldi", name: "カルディ", price: 598, inStock: true },
      { type: "aeon", name: "イオン", price: 578, inStock: true },
      { type: "rakuten", name: "楽天市場", price: 548, inStock: true },
    ],
    buzzScore: 65,
    vivinoScore: 3.5,
    costPerformance: 90,
    tags: ["家飲み", "イタリアン", "パスタ"],
    tweetUrls: ["https://x.com/winenomuhito/status/2034762199059898505"],
    abv: 12.5,
    servingTemp: "14-16℃",
    pairings: ["ボロネーゼ", "ピザ", "トマト煮込み"],
    whyBuyNow: "カルディの隠れ定番。渋みが穏やかでイタリアン初心者に最適",
    buyLinks: [{ store: "Amazon", url: "https://www.amazon.co.jp/s?k=モンテプルチアーノ+ダブルッツォ+Citra", price: 548 }],
  },
  {
    id: "4",
    name: "Côtes du Rhône Rouge",
    nameJa: "コート・デュ・ローヌ ルージュ",
    producer: "E. Guigal",
    country: "France",
    countryCode: "FR",
    type: "red",
    grapeVarieties: ["グルナッシュ", "シラー", "ムールヴェードル"],
    description:
      "フランスワインなのにこの価格。スパイシーで深い味わい。1,000円台で本格ローヌが楽しめる。",
    price: 1380,
    stores: [
      { type: "kaldi", name: "カルディ", price: 1380, inStock: true },
      { type: "seijoishii", name: "成城石井", price: 1480, inStock: true },
      { type: "amazon", name: "Amazon", price: 1280, inStock: true },
    ],
    buzzScore: 60,
    vivinoScore: 3.8,
    costPerformance: 85,
    tags: ["手土産", "フランス", "本格派"],
    tweetUrls: ["https://x.com/winenomuhito/status/2034394085180751896"],
    abv: 14.5,
    servingTemp: "16-18℃",
    pairings: ["ビーフシチュー", "ラムチョップ", "チーズ"],
    whyBuyNow: "1,380円で飲める本格フランスワイン。ギガルの品質は別格",
    buyLinks: [{ store: "Amazon", url: "https://www.amazon.co.jp/s?k=ギガル+コートデュローヌ", price: 1280 }],
  },
  {
    id: "5",
    name: "Casillero del Diablo Pinot Noir",
    nameJa: "カッシェロ・デル・ディアブロ ピノ・ノワール",
    producer: "Concha y Toro",
    country: "Chile",
    countryCode: "CL",
    type: "red",
    grapeVarieties: ["ピノ・ノワール"],
    description:
      "千円以下でピノ・ノワールが飲める幸せ。チェリーやラズベリーの華やかな香り、和食にも合う。",
    price: 698,
    stores: [
      { type: "seven", name: "セブン-イレブン", price: 698, inStock: true },
      { type: "lawson", name: "ローソン", price: 698, inStock: true },
      { type: "amazon", name: "Amazon", price: 645, inStock: true },
    ],
    buzzScore: 75,
    vivinoScore: 3.6,
    costPerformance: 86,
    tags: ["家飲み", "和食", "コンビニ"],
    tweetUrls: ["https://x.com/winenomuhito/status/2033672789132251570"],
    abv: 13.0,
    servingTemp: "14-16℃",
    pairings: ["筑前煮", "鮭の塩焼き", "焼き鳥"],
    whyBuyNow: "698円でピノ・ノワール。和食にも寄り添う繊細な赤",
    buyLinks: [{ store: "Amazon", url: "https://www.amazon.co.jp/s?k=カッシェロデルディアブロ+ピノノワール", price: 645 }],
  },

  // ===== 白ワイン =====
  {
    id: "6",
    name: "Casillero del Diablo Chardonnay",
    nameJa: "カッシェロ・デル・ディアブロ シャルドネ",
    producer: "Concha y Toro",
    country: "Chile",
    countryCode: "CL",
    type: "white",
    grapeVarieties: ["シャルドネ"],
    description:
      "トロピカルフルーツとほのかな樽香。コンビニ白ワインの王者。魚料理からチキンまで万能。",
    price: 698,
    stores: [
      { type: "seven", name: "セブン-イレブン", price: 698, inStock: true },
      { type: "lawson", name: "ローソン", price: 698, inStock: true },
      { type: "familymart", name: "ファミリーマート", price: 698, inStock: true },
      { type: "amazon", name: "Amazon", price: 645, inStock: true },
    ],
    buzzScore: 80,
    vivinoScore: 3.6,
    costPerformance: 89,
    tags: ["家飲み", "魚料理", "コンビニ", "万能"],
    tweetUrls: ["https://x.com/the_wild_hunt/status/2034357346185683379"],
    abv: 13.5,
    servingTemp: "8-10℃",
    pairings: ["刺身", "天ぷら", "チキングリル"],
    whyBuyNow: "コンビニ白No.1。トロピカルな樽香が698円で味わえる",
    buyLinks: [{ store: "Amazon", url: "https://www.amazon.co.jp/s?k=カッシェロデルディアブロ+シャルドネ", price: 645 }],
  },
  {
    id: "7",
    name: "Santa Rita 120 Sauvignon Blanc",
    nameJa: "サンタ・リタ 120 ソーヴィニヨン・ブラン",
    producer: "Santa Rita",
    country: "Chile",
    countryCode: "CL",
    type: "white",
    grapeVarieties: ["ソーヴィニヨン・ブラン"],
    description:
      "柑橘系の爽やかアロマ。キリッとした酸味がサラダや刺身と最高のマリアージュ。",
    price: 550,
    stores: [
      { type: "aeon", name: "イオン", price: 550, inStock: true },
      { type: "donki", name: "ドン・キホーテ", price: 528, inStock: true },
      { type: "rakuten", name: "楽天市場", price: 498, inStock: true },
    ],
    buzzScore: 65,
    vivinoScore: 3.4,
    costPerformance: 91,
    tags: ["家飲み", "刺身", "ワンコイン"],
    tweetUrls: ["https://x.com/winenomuhito/status/2033673519557710016"],
    abv: 13.0,
    servingTemp: "6-8℃",
    pairings: ["刺身", "サラダ", "冷奴"],
    whyBuyNow: "500円台で爽やかソーヴィニヨン・ブラン。キリッと冷やして",
    buyLinks: [{ store: "Amazon", url: "https://www.amazon.co.jp/s?k=サンタリタ+120+ソーヴィニヨンブラン", price: 498 }],
  },
  {
    id: "8",
    name: "Bogle Chardonnay",
    nameJa: "ボーグル シャルドネ",
    producer: "Bogle Vineyards",
    country: "USA",
    countryCode: "US",
    type: "white",
    grapeVarieties: ["シャルドネ"],
    description:
      "カリフォルニアの太陽を詰め込んだリッチな白。バター感とバニラ香が心地よく、SNSで大人気。",
    price: 1580,
    stores: [
      { type: "costco", name: "コストコ", price: 1298, inStock: true },
      { type: "seijoishii", name: "成城石井", price: 1580, inStock: true },
      { type: "amazon", name: "Amazon", price: 1480, inStock: true },
    ],
    buzzScore: 60,
    vivinoScore: 3.9,
    costPerformance: 87,
    tags: ["SNS話題", "手土産", "リッチ"],
    tweetUrls: ["https://x.com/winenomuhito/status/2034767134145085793"],
    abv: 14.5,
    servingTemp: "10-12℃",
    pairings: ["クリームパスタ", "グラタン", "ロティサリーチキン"],
    whyBuyNow: "コストコで1,298円。カリフォルニアのリッチ白がこの価格は反則",
    buyLinks: [{ store: "Amazon", url: "https://www.amazon.co.jp/s?k=ボーグル+シャルドネ", price: 1480 }],
  },
  {
    id: "9",
    name: "Torrontés",
    nameJa: "トロンテス",
    producer: "Colomé",
    country: "Argentina",
    countryCode: "AR",
    type: "white",
    grapeVarieties: ["トロンテス"],
    description:
      "マスカットのようなアロマティックな香り。華やかだけどドライで食事に合う。知る人ぞ知る逸品。",
    price: 1280,
    stores: [
      { type: "kaldi", name: "カルディ", price: 1280, inStock: true },
      { type: "liquor_shop", name: "やまや", price: 1180, inStock: true },
      { type: "rakuten", name: "楽天市場", price: 1150, inStock: true },
    ],
    buzzScore: 55,
    vivinoScore: 3.6,
    costPerformance: 84,
    tags: ["アロマティック", "新発見", "エスニック"],
    tweetUrls: ["https://x.com/winenomuhito/status/2033307192301105209"],
    abv: 13.5,
    servingTemp: "8-10℃",
    pairings: ["タイ料理", "エスニック", "生春巻き"],
    whyBuyNow: "マスカットの香りなのに辛口。エスニック料理との相性が異次元",
    buyLinks: [{ store: "Amazon", url: "https://www.amazon.co.jp/s?k=トロンテス+コロメ", price: 1150 }],
  },
  {
    id: "10",
    name: "Cloudy Bay Sauvignon Blanc",
    nameJa: "クラウディー・ベイ ソーヴィニヨン・ブラン",
    producer: "Cloudy Bay",
    country: "New Zealand",
    countryCode: "NZ",
    type: "white",
    grapeVarieties: ["ソーヴィニヨン・ブラン"],
    description:
      "NZソーヴィニヨン・ブランの代名詞。パッションフルーツとハーブの爽快感。奮発する日に。",
    price: 2980,
    stores: [
      { type: "seijoishii", name: "成城石井", price: 2980, inStock: true },
      { type: "amazon", name: "Amazon", price: 2780, inStock: true },
      { type: "rakuten", name: "楽天市場", price: 2680, inStock: true },
    ],
    buzzScore: 70,
    vivinoScore: 4.2,
    costPerformance: 75,
    tags: ["ご褒美", "手土産", "定番"],
    tweetUrls: ["https://x.com/winenomuhito/status/2034765764910293155"],
    abv: 13.5,
    servingTemp: "6-8℃",
    pairings: ["牡蠣", "白身魚", "シーフードサラダ"],
    whyBuyNow: "NZソーヴィニヨン・ブランの教科書。手土産に持てば必ず喜ばれる",
    buyLinks: [{ store: "Amazon", url: "https://www.amazon.co.jp/s?k=クラウディーベイ+ソーヴィニヨンブラン", price: 2780 }],
  },

  // ===== ロゼ =====
  {
    id: "11",
    name: "Mateus Rosé",
    nameJa: "マテウス ロゼ",
    producer: "Sogrape",
    country: "Portugal",
    countryCode: "PT",
    type: "rose",
    grapeVarieties: ["バガ", "ルフェテ", "トゥリガ・ナシオナル"],
    description:
      "世界で最も売れているロゼワイン。微発泡でフルーティ。ピクニックやBBQの定番。",
    price: 780,
    stores: [
      { type: "aeon", name: "イオン", price: 780, inStock: true },
      { type: "kaldi", name: "カルディ", price: 820, inStock: true },
      { type: "amazon", name: "Amazon", price: 698, inStock: true },
    ],
    buzzScore: 75,
    vivinoScore: 3.6,
    costPerformance: 83,
    tags: ["BBQ", "ピクニック", "微発泡"],
    tweetUrls: ["https://x.com/catlacatla/status/2007373239987916815", "https://x.com/shimas1ma/status/1965399969571242044", "https://x.com/SAKEYASU_by_SL/status/1953018839920234973"],
    abv: 11.0,
    servingTemp: "6-8℃",
    pairings: ["BBQ", "サンドイッチ", "フルーツ"],
    whyBuyNow: "世界で最も売れているロゼ。微発泡でBBQやピクニックの正解",
    buyLinks: [{ store: "Amazon", url: "https://www.amazon.co.jp/s?k=マテウス+ロゼ", price: 698 }],
  },
  {
    id: "12",
    name: "Whispering Angel Rosé",
    nameJa: "ウィスパリング・エンジェル ロゼ",
    producer: "Château d'Esclans",
    country: "France",
    countryCode: "FR",
    type: "rose",
    grapeVarieties: ["グルナッシュ", "サンソー", "ロール"],
    description:
      "インスタ映えNo.1ロゼ。淡いサーモンピンクの美しさと繊細な味わい。パーティの主役に。",
    price: 2480,
    stores: [
      { type: "seijoishii", name: "成城石井", price: 2480, inStock: true },
      { type: "amazon", name: "Amazon", price: 2280, inStock: true },
      { type: "rakuten", name: "楽天市場", price: 2180, inStock: true },
    ],
    buzzScore: 85,
    vivinoScore: 3.8,
    costPerformance: 72,
    tags: ["SNS話題", "パーティ", "おしゃれ", "ご褒美"],
    tweetUrls: ["https://x.com/Takocha92099042/status/2024626942000164888", "https://x.com/1223taisetu/status/1947261890280964479", "https://x.com/karimarupoko/status/1936210339697242619"],
    abv: 13.0,
    servingTemp: "8-10℃",
    pairings: ["カルパッチョ", "生ハム", "前菜全般"],
    whyBuyNow: "インスタ映えNo.1ロゼ。味も見た目もパーティの主役",
    buyLinks: [{ store: "Amazon", url: "https://www.amazon.co.jp/s?k=ウィスパリングエンジェル+ロゼ", price: 2280 }],
  },

  // ===== スパークリング =====
  {
    id: "13",
    name: "Freixenet Cordon Negro Brut",
    nameJa: "フレシネ コルドン・ネグロ ブリュット",
    producer: "Freixenet",
    country: "Spain",
    countryCode: "ES",
    type: "sparkling",
    grapeVarieties: ["マカベオ", "パレリャーダ", "チャレッロ"],
    description:
      "コンビニで買える本格カヴァ。黒ボトルがかっこいい。辛口で食事にも合う万能スパークリング。",
    price: 1098,
    stores: [
      { type: "seven", name: "セブン-イレブン", price: 1098, inStock: true },
      { type: "lawson", name: "ローソン", price: 1098, inStock: true },
      { type: "aeon", name: "イオン", price: 998, inStock: true },
      { type: "amazon", name: "Amazon", price: 928, inStock: true },
    ],
    buzzScore: 80,
    vivinoScore: 3.5,
    costPerformance: 88,
    tags: ["パーティ", "コンビニ", "乾杯"],
    tweetUrls: ["https://x.com/q9fVBAfv0817uI5/status/1992543064544735279", "https://x.com/69natsumi69/status/1988629139197227134"],
    abv: 11.5,
    servingTemp: "6-8℃",
    pairings: ["生ハム", "チーズ", "枝豆"],
    whyBuyNow: "コンビニで買える本格カヴァ。黒ボトルの辛口泡で乾杯",
    buyLinks: [{ store: "Amazon", url: "https://www.amazon.co.jp/s?k=フレシネ+コルドンネグロ", price: 928 }],
  },
  {
    id: "14",
    name: "Martini Asti Spumante",
    nameJa: "マルティーニ アスティ・スプマンテ",
    producer: "Martini & Rossi",
    country: "Italy",
    countryCode: "IT",
    type: "sparkling",
    grapeVarieties: ["モスカート"],
    description:
      "マスカットの甘い香り。甘口だけど重くない。ワイン初心者やスイーツとのペアリングに最適。",
    price: 1280,
    stores: [
      { type: "aeon", name: "イオン", price: 1280, inStock: true },
      { type: "donki", name: "ドン・キホーテ", price: 1180, inStock: true },
      { type: "amazon", name: "Amazon", price: 1098, inStock: true },
    ],
    buzzScore: 65,
    vivinoScore: 3.7,
    costPerformance: 82,
    tags: ["初心者", "スイーツ", "女子会"],
    tweetUrls: ["https://x.com/winenomuhito/status/2034394088632660363"],
    abv: 7.5,
    servingTemp: "4-6℃",
    pairings: ["フルーツタルト", "パンケーキ", "チョコレート"],
    whyBuyNow: "ワイン苦手な人もこれなら飲める。マスカットの甘い泡",
    buyLinks: [{ store: "Amazon", url: "https://www.amazon.co.jp/s?k=マルティーニ+アスティスプマンテ", price: 1098 }],
  },
  {
    id: "15",
    name: "Chandon Brut",
    nameJa: "シャンドン ブリュット",
    producer: "Domaine Chandon",
    country: "Australia",
    countryCode: "AU",
    type: "sparkling",
    grapeVarieties: ["シャルドネ", "ピノ・ノワール"],
    description:
      "モエ系列のプレミアム泡。シャンパンに迫るクオリティで半額以下。記念日やお祝いに。",
    price: 1980,
    stores: [
      { type: "seijoishii", name: "成城石井", price: 1980, inStock: true },
      { type: "costco", name: "コストコ", price: 1680, inStock: true },
      { type: "amazon", name: "Amazon", price: 1780, inStock: true },
    ],
    buzzScore: 75,
    vivinoScore: 3.8,
    costPerformance: 86,
    tags: ["記念日", "手土産", "プレミアム"],
    tweetUrls: ["https://x.com/winenomuhito/status/2035123277417652459"],
    abv: 12.5,
    servingTemp: "6-8℃",
    pairings: ["寿司", "天ぷら", "フレンチ前菜"],
    whyBuyNow: "モエ系列で2,000円以下。シャンパンに迫る泡を日常に",
    buyLinks: [{ store: "Amazon", url: "https://www.amazon.co.jp/s?k=シャンドン+ブリュット", price: 1780 }],
  },
  {
    id: "16",
    name: "Codorníu Clásico Seco",
    nameJa: "コドーニュ クラシコ セコ",
    producer: "Codorníu",
    country: "Spain",
    countryCode: "ES",
    type: "sparkling",
    grapeVarieties: ["マカベオ", "チャレッロ", "パレリャーダ"],
    description:
      "世界最古のカヴァ生産者。キレのある辛口泡が500円台。普段の食卓にシュワッと贅沢を。",
    price: 598,
    stores: [
      { type: "donki", name: "ドン・キホーテ", price: 598, inStock: true },
      { type: "aeon", name: "イオン", price: 628, inStock: true },
      { type: "rakuten", name: "楽天市場", price: 548, inStock: true },
    ],
    buzzScore: 60,
    vivinoScore: 3.4,
    costPerformance: 93,
    tags: ["ワンコイン", "家飲み", "コスパ最強"],
    tweetUrls: [],
    abv: 11.5,
    servingTemp: "6-8℃",
    pairings: ["ポテチ", "唐揚げ", "ピザ"],
    whyBuyNow: "500円台の辛口泡。世界最古のカヴァ生産者の実力",
    buyLinks: [{ store: "Amazon", url: "https://www.amazon.co.jp/s?k=コドーニュ+クラシコ+セコ", price: 548 }],
  },

  // ===== ちょっと贅沢（〜5,000円） =====
  {
    id: "17",
    name: "Louis Jadot Bourgogne Chardonnay",
    nameJa: "ルイ・ジャド ブルゴーニュ シャルドネ",
    producer: "Louis Jadot",
    country: "France",
    countryCode: "FR",
    type: "white",
    grapeVarieties: ["シャルドネ"],
    description:
      "本場ブルゴーニュの白がこの価格。上品なミネラル感と果実味のバランス。ワンランク上の食卓に。",
    price: 2480,
    stores: [
      { type: "seijoishii", name: "成城石井", price: 2480, inStock: true },
      { type: "liquor_shop", name: "やまや", price: 2380, inStock: true },
      { type: "amazon", name: "Amazon", price: 2200, inStock: true },
    ],
    buzzScore: 55,
    vivinoScore: 3.7,
    costPerformance: 80,
    tags: ["手土産", "ブルゴーニュ", "ご褒美"],
    tweetUrls: [],
    abv: 13.0,
    servingTemp: "10-12℃",
    pairings: ["バターソテー", "クリーム系", "白身魚"],
    whyBuyNow: "2,480円で本場ブルゴーニュ体験。ミネラル感がたまらない",
    buyLinks: [{ store: "Amazon", url: "https://www.amazon.co.jp/s?k=ルイジャド+ブルゴーニュ+シャルドネ", price: 2200 }],
  },
  {
    id: "18",
    name: "Oyster Bay Pinot Noir",
    nameJa: "オイスター・ベイ ピノ・ノワール",
    producer: "Oyster Bay",
    country: "New Zealand",
    countryCode: "NZ",
    type: "red",
    grapeVarieties: ["ピノ・ノワール"],
    description:
      "NZ産ピノの実力。チェリーとスパイスの絶妙バランス。鶏肉やサーモンとの相性が神。",
    price: 1980,
    stores: [
      { type: "seijoishii", name: "成城石井", price: 1980, inStock: true },
      { type: "kaldi", name: "カルディ", price: 1980, inStock: true },
      { type: "amazon", name: "Amazon", price: 1780, inStock: true },
    ],
    buzzScore: 70,
    vivinoScore: 3.8,
    costPerformance: 83,
    tags: ["SNS話題", "鶏肉", "サーモン"],
    tweetUrls: [],
    abv: 13.0,
    servingTemp: "14-16℃",
    pairings: ["サーモンムニエル", "鶏の照り焼き", "きのこリゾット"],
    whyBuyNow: "NZピノの実力派。サーモンとの相性は神レベル",
    buyLinks: [{ store: "Amazon", url: "https://www.amazon.co.jp/s?k=オイスターベイ+ピノノワール", price: 1780 }],
  },
  {
    id: "19",
    name: "Mionetto Prosecco Brut",
    nameJa: "ミオネット プロセッコ ブリュット",
    producer: "Mionetto",
    country: "Italy",
    countryCode: "IT",
    type: "sparkling",
    grapeVarieties: ["グレーラ"],
    description:
      "イタリアのプロセッコ人気を牽引。フルーティで飲みやすい泡。アペロール・スプリッツにも。",
    price: 1580,
    stores: [
      { type: "kaldi", name: "カルディ", price: 1580, inStock: true },
      { type: "costco", name: "コストコ", price: 1380, inStock: true },
      { type: "amazon", name: "Amazon", price: 1450, inStock: true },
    ],
    buzzScore: 65,
    vivinoScore: 3.7,
    costPerformance: 84,
    tags: ["SNS話題", "アペロール", "パーティ"],
    tweetUrls: [],
    abv: 11.0,
    servingTemp: "6-8℃",
    pairings: ["アペロール・スプリッツ", "生ハムメロン", "カプレーゼ"],
    whyBuyNow: "プロセッコ人気を牽引。フルーティ泡でおうちバー開店",
    buyLinks: [{ store: "Amazon", url: "https://www.amazon.co.jp/s?k=ミオネット+プロセッコ", price: 1450 }],
  },
  {
    id: "20",
    name: "Familia Zuccardi Serie A Malbec",
    nameJa: "ズッカルディ セリエA マルベック",
    producer: "Familia Zuccardi",
    country: "Argentina",
    countryCode: "AR",
    type: "red",
    grapeVarieties: ["マルベック"],
    description:
      "アルゼンチンの星。濃厚な果実味とスモーキーな余韻。BBQやステーキに合わせたい。",
    price: 1480,
    stores: [
      { type: "kaldi", name: "カルディ", price: 1480, inStock: true },
      { type: "liquor_shop", name: "やまや", price: 1380, inStock: true },
      { type: "rakuten", name: "楽天市場", price: 1280, inStock: true },
    ],
    buzzScore: 70,
    vivinoScore: 3.9,
    costPerformance: 86,
    tags: ["BBQ", "ステーキ", "濃厚"],
    tweetUrls: [],
    abv: 14.0,
    servingTemp: "16-18℃",
    pairings: ["ステーキ", "BBQ", "焼肉"],
    whyBuyNow: "アルゼンチンマルベックの星。濃厚×スモーキーで肉料理の最強相棒",
    buyLinks: [{ store: "Amazon", url: "https://www.amazon.co.jp/s?k=ズッカルディ+マルベック", price: 1280 }],
  },
];

/** 店舗名のラベル */
export const storeLabels: Record<string, string> = {
  seven: "セブン",
  lawson: "ローソン",
  familymart: "ファミマ",
  aeon: "イオン",
  seijoishii: "成城石井",
  kaldi: "カルディ",
  donki: "ドンキ",
  costco: "コストコ",
  rakuten: "楽天",
  amazon: "Amazon",
  liquor_shop: "酒屋",
};

/** 店舗別おすすめツイート（GROKから取得） */
export const storeRecommendedTweets: Record<string, string[]> = {
  seven: ["https://x.com/miiiokonno0309/status/2032105379904282875"],
  lawson: ["https://x.com/herakuresun/status/2034857066716963105", "https://x.com/SUPERsakurabon/status/2029970004977070406"],
  aeon: ["https://x.com/rock37uru69/status/2034885347243696404"],
  kaldi: ["https://x.com/AvixenA/status/2034974802445050178", "https://x.com/suzu46_ss/status/2034585551081537671"],
  costco: ["https://x.com/Unakichi_maxima/status/2033905058501562879"],
};
